### ISSUE TITLE
Simpler wrapper fn

### ISSUE THREAD

**Issue by mshwery** [davidbanham/express-async-errors#1]
First off: nice little library, thanks!

Would it be simpler to do something like this for the wrapper function?
```js
const wrap = (fn) => (req, res, next) => {
  Promise.resolve(fn(req, res, next))
    .catch(next)
}
```

If you're using `async` you _should_ also have support for `Promise`. And this gets around any issues with the wrapped function _not being async/promise-based_, by wrapping it directly in a Promise, which also avoids the need to check for `catch` as a function on the function return.

What do you think about this?

**Comment by davidbanham** [comment]
Firstly, thankyou and apologies for not replying to this issue sooner. I think I need to sort out my GH notifications.

I've implemented your suggestion in a branch. It passes the tests and satisfies the constraints of a simple project I tried to drop it into.

The only possible hole I can see is, what happens if there's some downstream middleware supplied by a third party package that will flip out about being handed a Promise? That may well be Not A Thing, (and if it's obvious to you that it isn't please tell me) but I just want to let the thought marinate for a day or two and investigate a little further before pulling the trigger on the merge.

Again, thanks! Very clever simplification.

**Comment by mshwery** [comment]
@davidbanham no worries.

>The only possible hole I can see is, what happens if there's some downstream middleware supplied by a third party package that will flip out about being handed a Promise

You are right – though I don't think most Express middleware or route handlers _expect_ a return value, whether `Promise` or otherwise. I'm not sure I can 100% say it's "Not A Thing" but, I don't fully grok this being a problem. Now, the one area where something like this would definitely be a gotcha is when using other monkey-patches that might modify how middleware are handled (exactly like this module).

The beauty of using `Promise.resolve` is that it simply executes the function (any type of function, including `async` functions), and then the `catch` will handle any uncaught exceptions.

You could extend this to handle both types of middleware (normal _and_ error handlers):

```js
function wrap (fn) {
  if (fn.length <= 3) {
    return (req, res, next) => {
      return Promise.resolve(fn(req, res, next)).catch(next)
    }
  } else {
    return (error, req, res, next) => {
      return Promise.resolve(fn(error, req, res, next)).catch(next)
    }
  }
}
```

I'm not sure how Express will interpret Node 8.x spread/rest arguments, but that _could_ make it even sweeter, but maybe too clever:

```js
function wrap (fn) {
  return (...args) => Promise.resolve(fn(...args)).catch(next)
}
```

It all depends on how the returned function signature is interpreted: `([unknownArguments,])` or `(err, req, res, next)` + `(req, res, next)`

**Comment by scottmas** [comment]
The latest patch always wraps the function and most importantly to your concern, also returns the return value, whatever it may be. 

As for simplifying the wrapper function, Express stupidly relies on function arity (the number of arguments specified in the function signature) to detect error middleware. This is properly accounted for now too. 

So I think we can close this.
