### ISSUE TITLE
Express-async-errors doesn't work

### ISSUE THREAD

**Issue by AlexMachin1997** [davidbanham/express-async-errors#15]
Hi,

So I'm following a Udemy course online and as one of the parts, it integrates your plugin. Apparently, all you do is require it and it works, though this isn't the case for me. 

The module just refuses to work, it doesn't catch any issues, it behaves as if the package doesn't exist. I just get presented with a timeout response in Postman the API client.

**Comment by davidbanham** [comment]
Hi Alex, which Udemy course?

You need to add it to the middleware stack as well as requiring it. Github issues are more about logging bugs with the code rather than asking for help in using it. There might be someone that has the time and the inclination to help you out, but without being able to see your code there's very little anyone can do. Try posting a jsfiddle that replicates your issue.

**Comment by aaronshivers** [comment]
Hello,

Here's the course that uses this package.
https://www.udemy.com/nodejs-master-class/

Here's my code from the project.
https://github.com/aaronshivers/vidly
Here's the file with the package.
https://github.com/aaronshivers/vidly/blob/master/startup/logging.js

I can't say if it works or not, but you can compare this to what you have in your project.

**Comment by davidbanham** [comment]
I've taken a quick look and everything related to express-async-errors is working as expected. Here's a quick POC:

https://github.com/aaronshivers/vidly/pull/1
