### ISSUE TITLE
ISC license violation

### ISSUE THREAD

**Issue by trueproof** [davidbanham/express-async-errors#22]
https://github.com/davidbanham/express-async-errors/commit/7882729169c22cb3efd2bc1fe8d3fa662fcff2a6#diff-04c6e90faac2675aa89e2176d2eec7d8L53

your commit removes copyright, but [ISC license](https://www.isc.org/licenses/) states that

"Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, **provided that the above copyright notice and this permission notice appear in all copies**."

any objections against "Copyright (C) 2016 Nikolay Nemshilov" line?

**Comment by davidbanham** [comment]
No objections at all from me.

For context, I originally washed Nikolay's name out of everything because he'd told me many times how frustrating he found it to deal with the maintenance of all his OSS projects and I didn't want to throw another one on his plate. At the time I emailed him to let him know what I'd done and why. He said he was uncomfortable with is name being removed so I re-added the attribution, made it an explicit fork on GH, etc etc. I must have forgotten to re-add the copyright line to the license file.
