### ISSUE TITLE
Problem with nested routers

### ISSUE THREAD

**Issue by standuprey** [davidbanham/express-async-errors#32]
I first had something like this

```
const router = express.Router();
const resourceRouter = express.Router();
router.use('/resource', resourceRouter);
resourceRouter.get('/', async (req, res) => {
  throw new Error('not good');
})

app.use('/api', router);
app.use((err, req, res, next) => {
  if (err.message === 'access denied') {
    res.status(403);
    res.json({ error: err.message });
  }

  next(err);
});

```

That would not catch the error, as a workaround, I am not using nested router anymore, only one router to rule them all

**Comment by standuprey** [comment]
I found the issue it was on my end and unrelated probably

**Comment by davidbanham** [comment]
Good result! Thanks for coming back and updating the issue 🙏

**Comment by dko-slapdash** [comment]
@standup75 still curious, what was the issue on your end? Because I now see exactly the same effect - a router nested in another router doesn't work and raises UnhandledPromiseRejectionWarning:

```
const waitlistRouter = Router()
  .get("/waitlist", waitlistList);

async function waitlistList(req: Request, res: Response) {
  throw Error("test");
}

const adminRouter = Router();
adminRouter.use(waitlistRouter);

app.use("/admin", adminRouter);
```

UnhandledPromiseRejectionWarning: Error: test

My question, is it intended to work at all or just not supported?

**Comment by dko-slapdash** [comment]
@davidbanham - could you please help with the answer on the above ^ ?

**Comment by dko-slapdash** [comment]
OK, so in my case, the reason why nested Routers didn't work is because express-async-errors was included not before the 1st usage of express, but somewhere in the middle (due to module resolution order). Once I moved `require("express-async-errors")` to the very top of the entry point, throwing exceptions in nested routes started working as expected (and no UnhandledPromiseRejectionWarning anymore).

**Comment by kronicker** [comment]
Hey @dko-slapdash since `express-async-errors` patches Express Router and param handler it's best that it's imported right after express as it's shown in the [docs](https://github.com/davidbanham/express-async-errors#usage).
